<?php
/**
 * @file
 * Initial example of alter functions.
 */

/**
 * Implements hook_form_alter().
 *
 * Adds some playful text to the search form.
 */
function glue_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'search_block_form') {
    $form['fun_text'] = array(
      '#markup' => '<p>Search our pages like a boss:</p>',
      '#weight' => -10,
    );
  }
}

/**
 * Implements hook_menu().
 */
function glue_menu() {
  return array(
    'hello-world' => array(
      'title' => 'Hello world page',
      'route_name' => 'hello_world',
    ),
  );
}
